dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --no-cache -t levivig/adventofcode . 
      - docker images
      - docker push $DOCKER_USERNAME/adventofcode
