services:
  - docker

before_install:
  - docker build --no-cache -t levivig/adventofcode . 
  - docker run levivig/adventofcode /bin/sh -c "./run.sh 1;"
  - docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

