sudo: required
services:
  - docker

script:
  - docker build --no-cache -t levivig/adventofcode . 
  - docker run levivig/adventofcode

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push levivig/adventofcode
  on:
    branch: master